#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_MNT_Beetle

#include "Basic.hpp"

#include "ABP_MNT_Template_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_MNT_Beetle.ABP_MNT_Beetle_C
// 0x0000 (0xD490 - 0xD490)
class UABP_MNT_Beetle_C final : public UABP_MNT_Template_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_MNT_Beetle_C">();
	}
	static class UABP_MNT_Beetle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_MNT_Beetle_C>();
	}
};
static_assert(alignof(UABP_MNT_Beetle_C) == 0x000010, "Wrong alignment on UABP_MNT_Beetle_C");
static_assert(sizeof(UABP_MNT_Beetle_C) == 0x00D490, "Wrong size on UABP_MNT_Beetle_C");

}

