#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_PC_MNT_Wyrmling

#include "Basic.hpp"

#include "ABP_PC_MNT_Gryphon_structs.hpp"


namespace SDK
{

// ScriptStruct ABP_PC_MNT_Wyrmling.ABP_PC_MNT_Wyrmling_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0390 - 0x0390)
struct ABP_PC_MNT_Wyrmling::FAnimBlueprintGeneratedConstantData final : public ABP_PC_MNT_Gryphon::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(ABP_PC_MNT_Wyrmling::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on ABP_PC_MNT_Wyrmling::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(ABP_PC_MNT_Wyrmling::FAnimBlueprintGeneratedConstantData) == 0x000390, "Wrong size on ABP_PC_MNT_Wyrmling::FAnimBlueprintGeneratedConstantData");

}

