#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Academic_Mount_Base_Vendor

#include "Basic.hpp"

#include "HumanoidNPCMaster_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Academic_Mount_Base_Vendor.Academic_Mount_Base_Vendor_C
// 0x0000 (0x1D70 - 0x1D70)
class AAcademic_Mount_Base_Vendor_C final : public AHumanoidNPCMaster_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Academic_Mount_Base_Vendor_C">();
	}
	static class AAcademic_Mount_Base_Vendor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAcademic_Mount_Base_Vendor_C>();
	}
};
static_assert(alignof(AAcademic_Mount_Base_Vendor_C) == 0x000010, "Wrong alignment on AAcademic_Mount_Base_Vendor_C");
static_assert(sizeof(AAcademic_Mount_Base_Vendor_C) == 0x001D70, "Wrong size on AAcademic_Mount_Base_Vendor_C");

}

