#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AoCAIControllerBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AoCAIControllerBP.AoCAIControllerBP_C
// 0x0010 (0x0480 - 0x0470)
class AAoCAIControllerBP_C final : public AAoCAIController
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0470(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAIPerceptionComponent*                 AIPerception;                                      // 0x0478(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_AoCAIControllerBP(int32 EntryPoint);
	void ReceivePossess(class APawn* PossessedPawn);
	void ReceiveUnPossess(class APawn* UnpossessedPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AoCAIControllerBP_C">();
	}
	static class AAoCAIControllerBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAoCAIControllerBP_C>();
	}
};
static_assert(alignof(AAoCAIControllerBP_C) == 0x000008, "Wrong alignment on AAoCAIControllerBP_C");
static_assert(sizeof(AAoCAIControllerBP_C) == 0x000480, "Wrong size on AAoCAIControllerBP_C");
static_assert(offsetof(AAoCAIControllerBP_C, UberGraphFrame) == 0x000470, "Member 'AAoCAIControllerBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AAoCAIControllerBP_C, AIPerception) == 0x000478, "Member 'AAoCAIControllerBP_C::AIPerception' has a wrong offset!");

}

