#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Bandit_Musician1_Pirate

#include "Basic.hpp"

#include "Bandit_Troubadour_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Bandit_Musician1_Pirate.Bandit_Musician1_Pirate_C
// 0x0000 (0x1DB0 - 0x1DB0)
class ABandit_Musician1_Pirate_C final : public ABandit_Troubadour_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Bandit_Musician1_Pirate_C">();
	}
	static class ABandit_Musician1_Pirate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABandit_Musician1_Pirate_C>();
	}
};
static_assert(alignof(ABandit_Musician1_Pirate_C) == 0x000010, "Wrong alignment on ABandit_Musician1_Pirate_C");
static_assert(sizeof(ABandit_Musician1_Pirate_C) == 0x001DB0, "Wrong size on ABandit_Musician1_Pirate_C");

}

