#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Bandit_Mage_Base

#include "Basic.hpp"


namespace SDK::Params
{

// Function Bandit_Mage_Base.Bandit_Mage_Base_C.ExecuteUbergraph_Bandit_Mage_Base
// 0x0004 (0x0004 - 0x0000)
struct Bandit_Mage_Base_C_ExecuteUbergraph_Bandit_Mage_Base final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Bandit_Mage_Base_C_ExecuteUbergraph_Bandit_Mage_Base) == 0x000004, "Wrong alignment on Bandit_Mage_Base_C_ExecuteUbergraph_Bandit_Mage_Base");
static_assert(sizeof(Bandit_Mage_Base_C_ExecuteUbergraph_Bandit_Mage_Base) == 0x000004, "Wrong size on Bandit_Mage_Base_C_ExecuteUbergraph_Bandit_Mage_Base");
static_assert(offsetof(Bandit_Mage_Base_C_ExecuteUbergraph_Bandit_Mage_Base, EntryPoint) == 0x000000, "Member 'Bandit_Mage_Base_C_ExecuteUbergraph_Bandit_Mage_Base::EntryPoint' has a wrong offset!");

}

