#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BiomeManager_V2

#include "Basic.hpp"

#include "BP_BiomeManager_V2_classes.hpp"
#include "BP_BiomeManager_V2_parameters.hpp"


namespace SDK
{

// Function BP_BiomeManager_V2.BP_BiomeManager_V2_C.BindToSkyTick
// (BlueprintCallable, BlueprintEvent)

void ABP_BiomeManager_V2_C::BindToSkyTick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BiomeManager_V2_C", "BindToSkyTick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BiomeManager_V2.BP_BiomeManager_V2_C.EditorTick
// (BlueprintCallable, BlueprintEvent)

void ABP_BiomeManager_V2_C::EditorTick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BiomeManager_V2_C", "EditorTick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BiomeManager_V2.BP_BiomeManager_V2_C.ExecuteUbergraph_BP_BiomeManager_V2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BiomeManager_V2_C::ExecuteUbergraph_BP_BiomeManager_V2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BiomeManager_V2_C", "ExecuteUbergraph_BP_BiomeManager_V2");

	Params::BP_BiomeManager_V2_C_ExecuteUbergraph_BP_BiomeManager_V2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BiomeManager_V2.BP_BiomeManager_V2_C.Game Tick
// (BlueprintCallable, BlueprintEvent)

void ABP_BiomeManager_V2_C::Game_Tick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BiomeManager_V2_C", "Game Tick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BiomeManager_V2.BP_BiomeManager_V2_C.GlobalSkyTickBP
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BiomeManager_V2_C::GlobalSkyTickBP(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BiomeManager_V2_C", "GlobalSkyTickBP");

	Params::BP_BiomeManager_V2_C_GlobalSkyTickBP Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BiomeManager_V2.BP_BiomeManager_V2_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_BiomeManager_V2_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BiomeManager_V2_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BiomeManager_V2.BP_BiomeManager_V2_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BiomeManager_V2_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BiomeManager_V2_C", "ReceiveTick");

	Params::BP_BiomeManager_V2_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BiomeManager_V2.BP_BiomeManager_V2_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_BiomeManager_V2_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BiomeManager_V2_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

