#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NavalVehicleBase

#include "Basic.hpp"

#include "BP_NavalVehicleBase_classes.hpp"
#include "BP_NavalVehicleBase_parameters.hpp"


namespace SDK
{

// Function BP_NavalVehicleBase.BP_NavalVehicleBase_C.ExecuteUbergraph_BP_NavalVehicleBase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_NavalVehicleBase_C::ExecuteUbergraph_BP_NavalVehicleBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NavalVehicleBase_C", "ExecuteUbergraph_BP_NavalVehicleBase");

	Params::BP_NavalVehicleBase_C_ExecuteUbergraph_BP_NavalVehicleBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_NavalVehicleBase.BP_NavalVehicleBase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_NavalVehicleBase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NavalVehicleBase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NavalVehicleBase.BP_NavalVehicleBase_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_NavalVehicleBase_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NavalVehicleBase_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

