#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Projectile_Ancients_Leader_LightningOrb

#include "Basic.hpp"

#include "BP_Projectile_Ancients_Leader_LightningOrb_classes.hpp"
#include "BP_Projectile_Ancients_Leader_LightningOrb_parameters.hpp"


namespace SDK
{

// Function BP_Projectile_Ancients_Leader_LightningOrb.BP_Projectile_Ancients_Leader_LightningOrb_C.ExecuteUbergraph_BP_Projectile_Ancients_Leader_LightningOrb
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Projectile_Ancients_Leader_LightningOrb_C::ExecuteUbergraph_BP_Projectile_Ancients_Leader_LightningOrb(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Projectile_Ancients_Leader_LightningOrb_C", "ExecuteUbergraph_BP_Projectile_Ancients_Leader_LightningOrb");

	Params::BP_Projectile_Ancients_Leader_LightningOrb_C_ExecuteUbergraph_BP_Projectile_Ancients_Leader_LightningOrb Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Projectile_Ancients_Leader_LightningOrb.BP_Projectile_Ancients_Leader_LightningOrb_C.ProjectileHit
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_Projectile_Ancients_Leader_LightningOrb_C::ProjectileHit(const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Projectile_Ancients_Leader_LightningOrb_C", "ProjectileHit");

	Params::BP_Projectile_Ancients_Leader_LightningOrb_C_ProjectileHit Parms{};

	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Projectile_Ancients_Leader_LightningOrb.BP_Projectile_Ancients_Leader_LightningOrb_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Projectile_Ancients_Leader_LightningOrb_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Projectile_Ancients_Leader_LightningOrb_C", "ReceiveTick");

	Params::BP_Projectile_Ancients_Leader_LightningOrb_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}

}

