#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cowering_NPC_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Cowering_NPC_AnimBP_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Cowering_NPC_AnimBP.Cowering_NPC_AnimBP_C
// 0x38D0 (0x49C0 - 0x10F0)
class UCowering_NPC_AnimBP_C final : public UAoCAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x10F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct Cowering_NPC_AnimBP::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;          // 0x10F8(0x0034)(HasGetValueTypeHash)
	uint8                                         Pad_112C[0x4];                                     // 0x112C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x1130(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x1138(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x1140(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21;                 // 0x1160(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20;                 // 0x1188(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19;                 // 0x11B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18;                 // 0x11D8(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_25;                   // 0x1200(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13;                      // 0x1248(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_24;                   // 0x1268(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12;                      // 0x12B0(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17;                 // 0x12D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16;                 // 0x12F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15;                 // 0x1320(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14;                 // 0x1348(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13;                 // 0x1370(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x1398(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x13C0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x13E8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x1410(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x1438(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x1460(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x1488(0x0028)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_3;                  // 0x14B0(0x0070)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11;                      // 0x1520(0x0020)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace_1;          // 0x1540(0x0118)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_27;                    // 0x1658(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10;                      // 0x1680(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_23;                   // 0x16A0(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9;                       // 0x16E8(0x0020)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_5;                   // 0x1708(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_26;                    // 0x1750(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_25;                    // 0x1778(0x0028)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace;            // 0x17A0(0x0118)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8;                       // 0x18B8(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x18D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x1900(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x1928(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x1950(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x1978(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x19A0(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_22;                   // 0x19C8(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7;                       // 0x1A10(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_21;                   // 0x1A30(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0x1A78(0x0020)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x1A98(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_4;                      // 0x1AB8(0x00C8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x1B80(0x0020)()
	struct FAnimNode_RandomPlayer                 AnimGraphNode_RandomPlayer;                        // 0x1BA0(0x0078)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x1C18(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_3;                      // 0x1C38(0x00C8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x1D00(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_2;                      // 0x1D20(0x00C8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x1DE8(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0x1E08(0x00C8)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_3;                              // 0x1ED0(0x0048)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_10;                   // 0x1F18(0x0080)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_15;                 // 0x1F98(0x00F0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_2;                              // 0x2088(0x0048)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_7;                   // 0x20D0(0x0048)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_3;                        // 0x2118(0x0128)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;             // 0x2240(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;             // 0x2260(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_2;                        // 0x2280(0x0128)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_20;                   // 0x23A8(0x0048)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_9;                    // 0x23F0(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_19;                   // 0x2470(0x0048)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_8;                    // 0x24B8(0x0080)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_2;                  // 0x2538(0x0070)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_1;                  // 0x25A8(0x0070)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_4;                   // 0x2618(0x0048)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_3;                   // 0x2660(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_24;                    // 0x26A8(0x0028)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_7;                    // 0x26D0(0x0080)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_6;                    // 0x2750(0x0080)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_5;                    // 0x27D0(0x0080)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_23;                    // 0x2850(0x0028)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_2;                   // 0x2878(0x0048)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_1;                   // 0x28C0(0x0048)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum;                     // 0x2908(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_22;                    // 0x2950(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_21;                    // 0x2978(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_20;                    // 0x29A0(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_19;                    // 0x29C8(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_18;                    // 0x29F0(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_17;                    // 0x2A18(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_16;                    // 0x2A40(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_15;                    // 0x2A68(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_14;                    // 0x2A90(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_13;                    // 0x2AB8(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_12;                    // 0x2AE0(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_11;                    // 0x2B08(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_18;                   // 0x2B30(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_17;                   // 0x2B78(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_16;                   // 0x2BC0(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_14;                 // 0x2C08(0x00F0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_6;                   // 0x2CF8(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_13;                 // 0x2D40(0x00F0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_15;                   // 0x2E30(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14;                   // 0x2E78(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x2EC0(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_12;                 // 0x2F08(0x00F0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_5;                   // 0x2FF8(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_11;                 // 0x3040(0x00F0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x3130(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x3178(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x31C0(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_10;                 // 0x3208(0x00F0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_4;                   // 0x32F8(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_9;                  // 0x3340(0x00F0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x3430(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x3478(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x34C0(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_8;                  // 0x3508(0x00F0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_3;                   // 0x35F8(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_7;                  // 0x3640(0x00F0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x3730(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x3778(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x37C0(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_6;                  // 0x3808(0x00F0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_2;                   // 0x38F8(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_5;                  // 0x3940(0x00F0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x3A30(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x3A78(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x3AC0(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_4;                  // 0x3B08(0x00F0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_1;                   // 0x3BF8(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_3;                  // 0x3C40(0x00F0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x3D30(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x3D50(0x00C8)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_10;                    // 0x3E18(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_9;                     // 0x3E40(0x0028)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x3E68(0x0070)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_4;                    // 0x3ED8(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x3F58(0x0048)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_3;                    // 0x3FA0(0x0080)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_8;                     // 0x4020(0x0028)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_2;                  // 0x4048(0x00F0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_7;                     // 0x4138(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_6;                     // 0x4160(0x0028)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_2;                    // 0x4188(0x0080)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_5;                     // 0x4208(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_4;                     // 0x4230(0x0028)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_1;                        // 0x4258(0x0128)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x4380(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x43A0(0x0128)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x44C8(0x0020)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1;                    // 0x44E8(0x0080)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_1;                  // 0x4568(0x00F0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3;                     // 0x4658(0x0028)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x4680(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x46C8(0x00F0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1;                              // 0x47B8(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x4800(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2;                     // 0x4848(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x4870(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x4898(0x0028)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x48C0(0x0080)()
	double                                        SpeedForward;                                      // 0x4940(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          InCombat;                                          // 0x4948(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsInAir_;                                          // 0x4949(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_494A[0x6];                                     // 0x494A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Velocity;                                          // 0x4950(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        TurnRate;                                          // 0x4958(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsWalking;                                         // 0x4960(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsDead;                                            // 0x4961(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4962[0x6];                                     // 0x4962(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               HeadRotation;                                      // 0x4968(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	double                                        Local_MaxHeadYaw;                                  // 0x4980(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        StartPosition;                                     // 0x4988(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DeadQuestGiver;                                    // 0x4990(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          RootMotionActive;                                  // 0x4991(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4992[0x6];                                     // 0x4992(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UAnimMontage*>                   IdleMontages;                                      // 0x4998(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UAnimMontage*>                   CombatMontages;                                    // 0x49A8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_BlendListByBool_70FC197543802E6E2710A29934216A25();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_12CFCBDD4D962B2438ECCBA21175A7CB();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_260C77D643FD013669C7C3A8BFB99ADF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_2D4B97034775AEE5436E229C07D81534();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_331081B44D8B4CE944F40BBDCFAF41C9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_3E3C391B4FD0AB8A1734B3BD0D440A6D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_432244D74B476A10DB4A15918605CDF3();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_4E035910415DCF799F243FA4BB814095();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_54C621C948A62320C6BD9A9D3886D321();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_59C3B36D449F85FC45C237900C199E3F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_5ACEC2504DF903BD0982A7A6C9D66071();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_6BC6143941EA40EDC14976BD8B9A852E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_7126A20347D8DE0E7A97FEA691F62C66();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_91486D3C4289F5C2ADA0918A72C58D84();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_B4D96F8C47576800E001D9AA64592D65();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Cowering_NPC_AnimBP_AnimGraphNode_TransitionResult_FB1C455B4EF6397516EEA2A160D94832();
	void ExecuteUbergraph_Cowering_NPC_AnimBP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Cowering_NPC_AnimBP_C">();
	}
	static class UCowering_NPC_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCowering_NPC_AnimBP_C>();
	}
};
static_assert(alignof(UCowering_NPC_AnimBP_C) == 0x000010, "Wrong alignment on UCowering_NPC_AnimBP_C");
static_assert(sizeof(UCowering_NPC_AnimBP_C) == 0x0049C0, "Wrong size on UCowering_NPC_AnimBP_C");
static_assert(offsetof(UCowering_NPC_AnimBP_C, UberGraphFrame) == 0x0010F0, "Member 'UCowering_NPC_AnimBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, __AnimBlueprintMutables) == 0x0010F8, "Member 'UCowering_NPC_AnimBP_C::__AnimBlueprintMutables' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimBlueprintExtension_PropertyAccess) == 0x001130, "Member 'UCowering_NPC_AnimBP_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimBlueprintExtension_Base) == 0x001138, "Member 'UCowering_NPC_AnimBP_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_Root) == 0x001140, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_21) == 0x001160, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_21' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_20) == 0x001188, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_20' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_19) == 0x0011B0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_19' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_18) == 0x0011D8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_18' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_25) == 0x001200, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_25' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateResult_13) == 0x001248, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateResult_13' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_24) == 0x001268, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_24' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateResult_12) == 0x0012B0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateResult_12' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_17) == 0x0012D0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_17' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_16) == 0x0012F8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_16' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_15) == 0x001320, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_15' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_14) == 0x001348, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_14' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_13) == 0x001370, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_13' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_12) == 0x001398, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_12' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_11) == 0x0013C0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_11' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_10) == 0x0013E8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_10' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_9) == 0x001410, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_9' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_8) == 0x001438, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_8' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_7) == 0x001460, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_7' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_6) == 0x001488, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_6' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendSpacePlayer_3) == 0x0014B0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendSpacePlayer_3' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateResult_11) == 0x001520, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateResult_11' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_RotationOffsetBlendSpace_1) == 0x001540, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_RotationOffsetBlendSpace_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_27) == 0x001658, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_27' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateResult_10) == 0x001680, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateResult_10' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_23) == 0x0016A0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_23' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateResult_9) == 0x0016E8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateResult_9' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendListByEnum_5) == 0x001708, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendListByEnum_5' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_26) == 0x001750, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_26' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_25) == 0x001778, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_25' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_RotationOffsetBlendSpace) == 0x0017A0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_RotationOffsetBlendSpace' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateResult_8) == 0x0018B8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateResult_8' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_5) == 0x0018D8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_4) == 0x001900, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_3) == 0x001928, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_2) == 0x001950, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult_1) == 0x001978, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_TransitionResult) == 0x0019A0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_22) == 0x0019C8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_22' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateResult_7) == 0x001A10, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateResult_7' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_21) == 0x001A30, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_21' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateResult_6) == 0x001A78, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateResult_6' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateResult_5) == 0x001A98, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateResult_5' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateMachine_4) == 0x001AB8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateMachine_4' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateResult_4) == 0x001B80, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateResult_4' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_RandomPlayer) == 0x001BA0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_RandomPlayer' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateResult_3) == 0x001C18, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateMachine_3) == 0x001C38, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateMachine_3' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateResult_2) == 0x001D00, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateMachine_2) == 0x001D20, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateMachine_2' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateResult_1) == 0x001DE8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateMachine_1) == 0x001E08, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateMachine_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_Slot_3) == 0x001ED0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_Slot_3' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SaveCachedPose_10) == 0x001F18, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SaveCachedPose_10' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_15) == 0x001F98, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_15' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_Slot_2) == 0x002088, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_Slot_2' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendListByBool_7) == 0x0020D0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendListByBool_7' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_ModifyBone_3) == 0x002118, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_ModifyBone_3' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LocalToComponentSpace_1) == 0x002240, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LocalToComponentSpace_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_ComponentToLocalSpace_1) == 0x002260, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_ComponentToLocalSpace_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_ModifyBone_2) == 0x002280, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_ModifyBone_2' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_20) == 0x0023A8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_20' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SaveCachedPose_9) == 0x0023F0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SaveCachedPose_9' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_19) == 0x002470, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_19' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SaveCachedPose_8) == 0x0024B8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SaveCachedPose_8' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendSpacePlayer_2) == 0x002538, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendSpacePlayer_2' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendSpacePlayer_1) == 0x0025A8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendSpacePlayer_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendListByEnum_4) == 0x002618, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendListByEnum_4' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendListByEnum_3) == 0x002660, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendListByEnum_3' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_24) == 0x0026A8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_24' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SaveCachedPose_7) == 0x0026D0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SaveCachedPose_7' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SaveCachedPose_6) == 0x002750, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SaveCachedPose_6' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SaveCachedPose_5) == 0x0027D0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SaveCachedPose_5' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_23) == 0x002850, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_23' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendListByEnum_2) == 0x002878, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendListByEnum_2' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendListByEnum_1) == 0x0028C0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendListByEnum_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendListByEnum) == 0x002908, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendListByEnum' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_22) == 0x002950, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_22' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_21) == 0x002978, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_21' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_20) == 0x0029A0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_20' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_19) == 0x0029C8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_19' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_18) == 0x0029F0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_18' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_17) == 0x002A18, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_17' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_16) == 0x002A40, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_16' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_15) == 0x002A68, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_15' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_14) == 0x002A90, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_14' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_13) == 0x002AB8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_13' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_12) == 0x002AE0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_12' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_11) == 0x002B08, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_11' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_18) == 0x002B30, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_18' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_17) == 0x002B78, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_17' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_16) == 0x002BC0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_16' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_14) == 0x002C08, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_14' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendListByBool_6) == 0x002CF8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendListByBool_6' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_13) == 0x002D40, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_13' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_15) == 0x002E30, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_15' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_14) == 0x002E78, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_14' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_13) == 0x002EC0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_13' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_12) == 0x002F08, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_12' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendListByBool_5) == 0x002FF8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendListByBool_5' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_11) == 0x003040, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_11' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_12) == 0x003130, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_12' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_11) == 0x003178, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_11' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_10) == 0x0031C0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_10' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_10) == 0x003208, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_10' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendListByBool_4) == 0x0032F8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendListByBool_4' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_9) == 0x003340, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_9' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_9) == 0x003430, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_9' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_8) == 0x003478, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_8' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_7) == 0x0034C0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_7' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_8) == 0x003508, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_8' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendListByBool_3) == 0x0035F8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendListByBool_3' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_7) == 0x003640, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_7' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_6) == 0x003730, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_6' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_5) == 0x003778, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_5' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_4) == 0x0037C0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_4' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_6) == 0x003808, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_6' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendListByBool_2) == 0x0038F8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendListByBool_2' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_5) == 0x003940, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_5' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_3) == 0x003A30, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_2) == 0x003A78, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer_1) == 0x003AC0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_4) == 0x003B08, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_4' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendListByBool_1) == 0x003BF8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendListByBool_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_3) == 0x003C40, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_3' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateResult) == 0x003D30, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_StateMachine) == 0x003D50, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_10) == 0x003E18, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_10' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_9) == 0x003E40, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_9' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendSpacePlayer) == 0x003E68, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendSpacePlayer' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SaveCachedPose_4) == 0x003ED8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SaveCachedPose_4' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SequencePlayer) == 0x003F58, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SaveCachedPose_3) == 0x003FA0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SaveCachedPose_3' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_8) == 0x004020, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_8' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_2) == 0x004048, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_2' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_7) == 0x004138, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_7' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_6) == 0x004160, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_6' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SaveCachedPose_2) == 0x004188, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SaveCachedPose_2' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_5) == 0x004208, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_5' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_4) == 0x004230, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_4' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_ModifyBone_1) == 0x004258, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_ModifyBone_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LocalToComponentSpace) == 0x004380, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_ModifyBone) == 0x0043A0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_ModifyBone' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_ComponentToLocalSpace) == 0x0044C8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SaveCachedPose_1) == 0x0044E8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SaveCachedPose_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend_1) == 0x004568, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_3) == 0x004658, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_3' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_BlendListByBool) == 0x004680, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_LayeredBoneBlend) == 0x0046C8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_LayeredBoneBlend' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_Slot_1) == 0x0047B8, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_Slot_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_Slot) == 0x004800, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_Slot' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_2) == 0x004848, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_2' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose_1) == 0x004870, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_UseCachedPose) == 0x004898, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, AnimGraphNode_SaveCachedPose) == 0x0048C0, "Member 'UCowering_NPC_AnimBP_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, SpeedForward) == 0x004940, "Member 'UCowering_NPC_AnimBP_C::SpeedForward' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, InCombat) == 0x004948, "Member 'UCowering_NPC_AnimBP_C::InCombat' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, IsInAir_) == 0x004949, "Member 'UCowering_NPC_AnimBP_C::IsInAir_' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, Velocity) == 0x004950, "Member 'UCowering_NPC_AnimBP_C::Velocity' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, TurnRate) == 0x004958, "Member 'UCowering_NPC_AnimBP_C::TurnRate' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, IsWalking) == 0x004960, "Member 'UCowering_NPC_AnimBP_C::IsWalking' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, IsDead) == 0x004961, "Member 'UCowering_NPC_AnimBP_C::IsDead' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, HeadRotation) == 0x004968, "Member 'UCowering_NPC_AnimBP_C::HeadRotation' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, Local_MaxHeadYaw) == 0x004980, "Member 'UCowering_NPC_AnimBP_C::Local_MaxHeadYaw' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, StartPosition) == 0x004988, "Member 'UCowering_NPC_AnimBP_C::StartPosition' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, DeadQuestGiver) == 0x004990, "Member 'UCowering_NPC_AnimBP_C::DeadQuestGiver' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, RootMotionActive) == 0x004991, "Member 'UCowering_NPC_AnimBP_C::RootMotionActive' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, IdleMontages) == 0x004998, "Member 'UCowering_NPC_AnimBP_C::IdleMontages' has a wrong offset!");
static_assert(offsetof(UCowering_NPC_AnimBP_C, CombatMontages) == 0x0049A8, "Member 'UCowering_NPC_AnimBP_C::CombatMontages' has a wrong offset!");

}

