#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CS_EmptyCharacterSlotButton

#include "Basic.hpp"

#include "BaseAudioButtonStyle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CS_EmptyCharacterSlotButton.CS_EmptyCharacterSlotButton_C
// 0x0000 (0x0800 - 0x0800)
class UCS_EmptyCharacterSlotButton_C final : public UBaseAudioButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CS_EmptyCharacterSlotButton_C">();
	}
	static class UCS_EmptyCharacterSlotButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCS_EmptyCharacterSlotButton_C>();
	}
};
static_assert(alignof(UCS_EmptyCharacterSlotButton_C) == 0x000010, "Wrong alignment on UCS_EmptyCharacterSlotButton_C");
static_assert(sizeof(UCS_EmptyCharacterSlotButton_C) == 0x000800, "Wrong size on UCS_EmptyCharacterSlotButton_C");

}

