#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cultist

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HumanoidMonsterMaster_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Cultist.Cultist_C
// 0x0010 (0x1D70 - 0x1D60)
#pragma pack(push, 0x1)
class alignas(0x10) ACultist_C : public AHumanoidMonsterMaster_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Cultist_C;                          // 0x1D60(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_Cultist(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Cultist_C">();
	}
	static class ACultist_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACultist_C>();
	}
};
#pragma pack(pop)
static_assert(alignof(ACultist_C) == 0x000010, "Wrong alignment on ACultist_C");
static_assert(sizeof(ACultist_C) == 0x001D70, "Wrong size on ACultist_C");
static_assert(offsetof(ACultist_C, UberGraphFrame_Cultist_C) == 0x001D60, "Member 'ACultist_C::UberGraphFrame_Cultist_C' has a wrong offset!");

}

