#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FilterPCGDataIndex

#include "Basic.hpp"

#include "PCG_structs.hpp"
#include "PCG_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FilterPCGDataIndex.FilterPCGDataIndex_C
// 0x0028 (0x00B0 - 0x0088)
class UFilterPCGDataIndex_C final : public UPCGBlueprintElement
{
public:
	int32                                         Target_Index;                                      // 0x0088(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPCGDataCollection                     Out_Data_Collection;                               // 0x0090(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteWithContext(struct FPCGContext& InContext, const struct FPCGDataCollection& Input, struct FPCGDataCollection* Output);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FilterPCGDataIndex_C">();
	}
	static class UFilterPCGDataIndex_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFilterPCGDataIndex_C>();
	}
};
static_assert(alignof(UFilterPCGDataIndex_C) == 0x000008, "Wrong alignment on UFilterPCGDataIndex_C");
static_assert(sizeof(UFilterPCGDataIndex_C) == 0x0000B0, "Wrong size on UFilterPCGDataIndex_C");
static_assert(offsetof(UFilterPCGDataIndex_C, Target_Index) == 0x000088, "Member 'UFilterPCGDataIndex_C::Target_Index' has a wrong offset!");
static_assert(offsetof(UFilterPCGDataIndex_C, Out_Data_Collection) == 0x000090, "Member 'UFilterPCGDataIndex_C::Out_Data_Collection' has a wrong offset!");

}

