#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FlameElemental_AnimBP

#include "Basic.hpp"

#include "AnimatedArmor_Mage_AnimBP_structs.hpp"


namespace SDK
{

// ScriptStruct FlameElemental_AnimBP.FlameElemental_AnimBP_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0200 - 0x0200)
struct FlameElemental_AnimBP::FAnimBlueprintGeneratedConstantData final : public AnimatedArmor_Mage_AnimBP::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(FlameElemental_AnimBP::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on FlameElemental_AnimBP::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(FlameElemental_AnimBP::FAnimBlueprintGeneratedConstantData) == 0x000200, "Wrong size on FlameElemental_AnimBP::FAnimBlueprintGeneratedConstantData");

}

