#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hunting_Scorpion

#include "Basic.hpp"

#include "Hunting_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Hunting_Scorpion.Hunting_Scorpion_C
// 0x0000 (0x1D50 - 0x1D50)
class AHunting_Scorpion_C final : public AHunting_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Hunting_Scorpion_C">();
	}
	static class AHunting_Scorpion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHunting_Scorpion_C>();
	}
};
static_assert(alignof(AHunting_Scorpion_C) == 0x000010, "Wrong alignment on AHunting_Scorpion_C");
static_assert(sizeof(AHunting_Scorpion_C) == 0x001D50, "Wrong size on AHunting_Scorpion_C");

}

