#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_Ooze_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "NPC_Ooze_AnimBP_structs.hpp"
#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass NPC_Ooze_AnimBP.NPC_Ooze_AnimBP_C
// 0x1F70 (0x3BC0 - 0x1C50)
class UNPC_Ooze_AnimBP_C : public UAoCNPCAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1C50(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct NPC_Ooze_AnimBP::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;              // 0x1C58(0x0038)(HasGetValueTypeHash)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x1C90(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x1C98(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x1CA0(0x0020)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_4;                    // 0x1CC0(0x0080)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_12;                             // 0x1D40(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_20;                    // 0x1D88(0x0028)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_3;                    // 0x1DB0(0x0080)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_19;                    // 0x1E30(0x0028)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_7;                   // 0x1E58(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_11;                             // 0x1EA0(0x0048)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_2;                    // 0x1EE8(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_10;                             // 0x1F30(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_9;                              // 0x1F78(0x0048)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_6;                   // 0x1FC0(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_8;                              // 0x2008(0x0048)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_1;                    // 0x2050(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_7;                              // 0x2098(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_6;                              // 0x20E0(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_5;                              // 0x2128(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_18;                    // 0x2170(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_17;                    // 0x2198(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_16;                    // 0x21C0(0x0028)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_4;                              // 0x21E8(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_15;                    // 0x2230(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_14;                    // 0x2258(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_13;                    // 0x2280(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_12;                    // 0x22A8(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_11;                    // 0x22D0(0x0028)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_5;                   // 0x22F8(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_3;                              // 0x2340(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_10;                    // 0x2388(0x0028)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_2;                              // 0x23B0(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_9;                     // 0x23F8(0x0028)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_2;                       // 0x2420(0x00C8)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21;                 // 0x24E8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20;                 // 0x2510(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19;                 // 0x2538(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18;                 // 0x2560(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13;                      // 0x2588(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x25A8(0x0048)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_4;                   // 0x25F0(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x2638(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x2680(0x0048)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_3;                   // 0x26C8(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12;                      // 0x2710(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17;                 // 0x2730(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16;                 // 0x2758(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15;                 // 0x2780(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14;                 // 0x27A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13;                 // 0x27D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x27F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x2820(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x2848(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x2870(0x0048)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_2;                   // 0x28B8(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x2900(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11;                      // 0x2948(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x2968(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x2990(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x29B8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x29E0(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x2A08(0x0048)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_1;                   // 0x2A50(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x2A98(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10;                      // 0x2AE0(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x2B00(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x2B48(0x0048)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x2B90(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9;                       // 0x2BD8(0x0020)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8;                       // 0x2BF8(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_3;                      // 0x2C18(0x00C8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7;                       // 0x2CE0(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x2D00(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x2D28(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x2D50(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x2D78(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x2DA0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x2DC8(0x0028)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_2;                  // 0x2DF0(0x0070)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0x2E60(0x0020)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x2E80(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x2EA0(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x2EE8(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_1;                  // 0x2F08(0x0070)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt;                      // 0x2F78(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x2FC0(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x3008(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x3050(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_2;                      // 0x3070(0x00C8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x3138(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x3158(0x0070)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x31C8(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0x31E8(0x00C8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x32B0(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x32D0(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_2;                    // 0x3398(0x0080)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_8;                     // 0x3418(0x0028)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1;                              // 0x3440(0x0048)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace;            // 0x3488(0x0118)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_1;                  // 0x35A0(0x00F0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_7;                     // 0x3690(0x0028)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_1;                       // 0x36B8(0x00C8)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_6;                     // 0x3780(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_5;                     // 0x37A8(0x0028)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x37D0(0x00F0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_4;                     // 0x38C0(0x0028)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x38E8(0x00C8)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x39B0(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3;                     // 0x39F8(0x0028)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1;                    // 0x3A20(0x0080)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2;                     // 0x3AA0(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x3AC8(0x0028)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x3AF0(0x0080)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x3B70(0x0028)()
	bool                                          Activated;                                         // 0x3B98(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B99[0x7];                                     // 0x3B99(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        IdleMode;                                          // 0x3BA0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        AmbushHeight;                                      // 0x3BA8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DropStart;                                         // 0x3BB0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SelfDestructComplete;                              // 0x3BB1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void AnimNotify_NPCNotAttacking();
	void AnimNotify_SelfDestructComplete();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_NPC_Ooze_AnimBP_AnimGraphNode_BlendListByInt_55599D8843121928ECA444A1C4FA8E68();
	void ExecuteUbergraph_NPC_Ooze_AnimBP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NPC_Ooze_AnimBP_C">();
	}
	static class UNPC_Ooze_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNPC_Ooze_AnimBP_C>();
	}
};
static_assert(alignof(UNPC_Ooze_AnimBP_C) == 0x000010, "Wrong alignment on UNPC_Ooze_AnimBP_C");
static_assert(sizeof(UNPC_Ooze_AnimBP_C) == 0x003BC0, "Wrong size on UNPC_Ooze_AnimBP_C");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, UberGraphFrame) == 0x001C50, "Member 'UNPC_Ooze_AnimBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, __AnimBlueprintMutables) == 0x001C58, "Member 'UNPC_Ooze_AnimBP_C::__AnimBlueprintMutables' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimBlueprintExtension_PropertyAccess) == 0x001C90, "Member 'UNPC_Ooze_AnimBP_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimBlueprintExtension_Base) == 0x001C98, "Member 'UNPC_Ooze_AnimBP_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_Root) == 0x001CA0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SaveCachedPose_4) == 0x001CC0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SaveCachedPose_4' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_Slot_12) == 0x001D40, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_Slot_12' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_20) == 0x001D88, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_20' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SaveCachedPose_3) == 0x001DB0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SaveCachedPose_3' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_19) == 0x001E30, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_19' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_BlendListByBool_7) == 0x001E58, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_BlendListByBool_7' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_Slot_11) == 0x001EA0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_Slot_11' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_BlendListByInt_2) == 0x001EE8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_BlendListByInt_2' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_Slot_10) == 0x001F30, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_Slot_10' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_Slot_9) == 0x001F78, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_Slot_9' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_BlendListByBool_6) == 0x001FC0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_BlendListByBool_6' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_Slot_8) == 0x002008, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_Slot_8' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_BlendListByInt_1) == 0x002050, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_BlendListByInt_1' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_Slot_7) == 0x002098, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_Slot_7' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_Slot_6) == 0x0020E0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_Slot_6' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_Slot_5) == 0x002128, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_Slot_5' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_18) == 0x002170, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_18' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_17) == 0x002198, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_17' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_16) == 0x0021C0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_16' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_Slot_4) == 0x0021E8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_Slot_4' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_15) == 0x002230, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_15' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_14) == 0x002258, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_14' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_13) == 0x002280, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_13' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_12) == 0x0022A8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_12' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_11) == 0x0022D0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_11' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_BlendListByBool_5) == 0x0022F8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_BlendListByBool_5' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_Slot_3) == 0x002340, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_Slot_3' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_10) == 0x002388, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_10' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_Slot_2) == 0x0023B0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_Slot_2' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_9) == 0x0023F8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_9' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TwoWayBlend_2) == 0x002420, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TwoWayBlend_2' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_21) == 0x0024E8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_21' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_20) == 0x002510, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_20' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_19) == 0x002538, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_19' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_18) == 0x002560, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_18' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateResult_13) == 0x002588, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateResult_13' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SequencePlayer_11) == 0x0025A8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SequencePlayer_11' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_BlendListByBool_4) == 0x0025F0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_BlendListByBool_4' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SequencePlayer_10) == 0x002638, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SequencePlayer_10' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SequencePlayer_9) == 0x002680, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SequencePlayer_9' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_BlendListByBool_3) == 0x0026C8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_BlendListByBool_3' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateResult_12) == 0x002710, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateResult_12' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_17) == 0x002730, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_17' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_16) == 0x002758, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_16' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_15) == 0x002780, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_15' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_14) == 0x0027A8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_14' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_13) == 0x0027D0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_13' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_12) == 0x0027F8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_12' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_11) == 0x002820, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_11' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_10) == 0x002848, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_10' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SequencePlayer_8) == 0x002870, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SequencePlayer_8' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_BlendListByBool_2) == 0x0028B8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_BlendListByBool_2' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SequencePlayer_7) == 0x002900, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SequencePlayer_7' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateResult_11) == 0x002948, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateResult_11' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_9) == 0x002968, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_9' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_8) == 0x002990, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_8' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_7) == 0x0029B8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_7' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_6) == 0x0029E0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_6' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SequencePlayer_6) == 0x002A08, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SequencePlayer_6' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_BlendListByBool_1) == 0x002A50, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_BlendListByBool_1' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SequencePlayer_5) == 0x002A98, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SequencePlayer_5' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateResult_10) == 0x002AE0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateResult_10' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SequencePlayer_4) == 0x002B00, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SequencePlayer_4' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SequencePlayer_3) == 0x002B48, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_BlendListByBool) == 0x002B90, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateResult_9) == 0x002BD8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateResult_9' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateResult_8) == 0x002BF8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateResult_8' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateMachine_3) == 0x002C18, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateMachine_3' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateResult_7) == 0x002CE0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateResult_7' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_5) == 0x002D00, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_4) == 0x002D28, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_3) == 0x002D50, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_2) == 0x002D78, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult_1) == 0x002DA0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TransitionResult) == 0x002DC8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_BlendSpacePlayer_2) == 0x002DF0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_BlendSpacePlayer_2' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateResult_6) == 0x002E60, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateResult_6' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateResult_5) == 0x002E80, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateResult_5' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SequencePlayer_2) == 0x002EA0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateResult_4) == 0x002EE8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateResult_4' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_BlendSpacePlayer_1) == 0x002F08, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_BlendSpacePlayer_1' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_BlendListByInt) == 0x002F78, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_BlendListByInt' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SequencePlayer_1) == 0x002FC0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SequencePlayer) == 0x003008, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateResult_3) == 0x003050, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateMachine_2) == 0x003070, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateMachine_2' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateResult_2) == 0x003138, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_BlendSpacePlayer) == 0x003158, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_BlendSpacePlayer' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateResult_1) == 0x0031C8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateMachine_1) == 0x0031E8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateMachine_1' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateResult) == 0x0032B0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_StateMachine) == 0x0032D0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SaveCachedPose_2) == 0x003398, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SaveCachedPose_2' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_8) == 0x003418, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_8' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_Slot_1) == 0x003440, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_Slot_1' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_RotationOffsetBlendSpace) == 0x003488, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_RotationOffsetBlendSpace' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_LayeredBoneBlend_1) == 0x0035A0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_LayeredBoneBlend_1' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_7) == 0x003690, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_7' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TwoWayBlend_1) == 0x0036B8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TwoWayBlend_1' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_6) == 0x003780, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_6' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_5) == 0x0037A8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_5' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_LayeredBoneBlend) == 0x0037D0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_LayeredBoneBlend' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_4) == 0x0038C0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_4' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_TwoWayBlend) == 0x0038E8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_TwoWayBlend' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_Slot) == 0x0039B0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_Slot' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_3) == 0x0039F8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_3' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SaveCachedPose_1) == 0x003A20, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SaveCachedPose_1' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_2) == 0x003AA0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_2' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose_1) == 0x003AC8, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_SaveCachedPose) == 0x003AF0, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AnimGraphNode_UseCachedPose) == 0x003B70, "Member 'UNPC_Ooze_AnimBP_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, Activated) == 0x003B98, "Member 'UNPC_Ooze_AnimBP_C::Activated' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, IdleMode) == 0x003BA0, "Member 'UNPC_Ooze_AnimBP_C::IdleMode' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, AmbushHeight) == 0x003BA8, "Member 'UNPC_Ooze_AnimBP_C::AmbushHeight' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, DropStart) == 0x003BB0, "Member 'UNPC_Ooze_AnimBP_C::DropStart' has a wrong offset!");
static_assert(offsetof(UNPC_Ooze_AnimBP_C, SelfDestructComplete) == 0x003BB1, "Member 'UNPC_Ooze_AnimBP_C::SelfDestructComplete' has a wrong offset!");

}

