#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PCGP_Minerals

#include "Basic.hpp"

#include "S_PCGParamSet_Minerals_structs.hpp"
#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PCGP_Minerals.PCGP_Minerals_C
// 0x0020 (0x0070 - 0x0050)
class UPCGP_Minerals_C final : public UPCGParameterData
{
public:
	struct FS_PCGParamSet_Minerals                Mineral_Deposits;                                  // 0x0050(0x0020)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PCGP_Minerals_C">();
	}
	static class UPCGP_Minerals_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPCGP_Minerals_C>();
	}
};
static_assert(alignof(UPCGP_Minerals_C) == 0x000008, "Wrong alignment on UPCGP_Minerals_C");
static_assert(sizeof(UPCGP_Minerals_C) == 0x000070, "Wrong size on UPCGP_Minerals_C");
static_assert(offsetof(UPCGP_Minerals_C, Mineral_Deposits) == 0x000050, "Member 'UPCGP_Minerals_C::Mineral_Deposits' has a wrong offset!");

}

