#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ProcessingStation_Lumbermilling_T1

#include "Basic.hpp"

#include "ProcessingStation_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ProcessingStation_Lumbermilling_T1.ProcessingStation_Lumbermilling_T1_C
// 0x0000 (0x0618 - 0x0618)
class AProcessingStation_Lumbermilling_T1_C final : public AProcessingStation_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ProcessingStation_Lumbermilling_T1_C">();
	}
	static class AProcessingStation_Lumbermilling_T1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProcessingStation_Lumbermilling_T1_C>();
	}
};
static_assert(alignof(AProcessingStation_Lumbermilling_T1_C) == 0x000008, "Wrong alignment on AProcessingStation_Lumbermilling_T1_C");
static_assert(sizeof(AProcessingStation_Lumbermilling_T1_C) == 0x000618, "Wrong size on AProcessingStation_Lumbermilling_T1_C");

}

