#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ramekin_Base

#include "Basic.hpp"

#include "Ramekin_Base_classes.hpp"
#include "Ramekin_Base_parameters.hpp"


namespace SDK
{

// Function Ramekin_Base.Ramekin_Base_C.ExecuteUbergraph_Ramekin_Base
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ARamekin_Base_C::ExecuteUbergraph_Ramekin_Base(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ramekin_Base_C", "ExecuteUbergraph_Ramekin_Base");

	Params::Ramekin_Base_C_ExecuteUbergraph_Ramekin_Base Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ramekin_Base.Ramekin_Base_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ARamekin_Base_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ramekin_Base_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

