#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RightClickMenu

#include "Basic.hpp"

#include "RightClickMenu_classes.hpp"
#include "RightClickMenu_parameters.hpp"


namespace SDK
{

// Function RightClickMenu.RightClickMenu_C.GetBorderContainer
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPanelWidget*                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UPanelWidget* URightClickMenu_C::GetBorderContainer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RightClickMenu_C", "GetBorderContainer");

	Params::RightClickMenu_C_GetBorderContainer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function RightClickMenu.RightClickMenu_C.GetEvenBorderStyle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class UCommonBorderStyle>   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

TSubclassOf<class UCommonBorderStyle> URightClickMenu_C::GetEvenBorderStyle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RightClickMenu_C", "GetEvenBorderStyle");

	Params::RightClickMenu_C_GetEvenBorderStyle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function RightClickMenu.RightClickMenu_C.GetOddBorderStyle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class UCommonBorderStyle>   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

TSubclassOf<class UCommonBorderStyle> URightClickMenu_C::GetOddBorderStyle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RightClickMenu_C", "GetOddBorderStyle");

	Params::RightClickMenu_C_GetOddBorderStyle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

