#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ServiceBuilding_Forge_Vendor

#include "Basic.hpp"

#include "Node_NPC_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ServiceBuilding_Forge_Vendor.ServiceBuilding_Forge_Vendor_C
// 0x0000 (0x1D90 - 0x1D90)
class AServiceBuilding_Forge_Vendor_C final : public ANode_NPC_Master_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ServiceBuilding_Forge_Vendor_C">();
	}
	static class AServiceBuilding_Forge_Vendor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AServiceBuilding_Forge_Vendor_C>();
	}
};
static_assert(alignof(AServiceBuilding_Forge_Vendor_C) == 0x000010, "Wrong alignment on AServiceBuilding_Forge_Vendor_C");
static_assert(sizeof(AServiceBuilding_Forge_Vendor_C) == 0x001D90, "Wrong size on AServiceBuilding_Forge_Vendor_C");

}

