#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShowOnMapButton

#include "Basic.hpp"

#include "BaseAudioButtonStyle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ShowOnMapButton.ShowOnMapButton_C
// 0x0000 (0x0800 - 0x0800)
class UShowOnMapButton_C final : public UBaseAudioButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ShowOnMapButton_C">();
	}
	static class UShowOnMapButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UShowOnMapButton_C>();
	}
};
static_assert(alignof(UShowOnMapButton_C) == 0x000010, "Wrong alignment on UShowOnMapButton_C");
static_assert(sizeof(UShowOnMapButton_C) == 0x000800, "Wrong size on UShowOnMapButton_C");

}

