#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Spirit_Wolf_Dire

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Spirit_Wolf_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Spirit_Wolf_Dire.Spirit_Wolf_Dire_C
// 0x0000 (0x1DA0 - 0x1DA0)
class ASpirit_Wolf_Dire_C final : public ASpirit_Wolf_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Spirit_Wolf_Dire_C;                 // 0x1D98(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Spirit_Wolf_Dire(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Spirit_Wolf_Dire_C">();
	}
	static class ASpirit_Wolf_Dire_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASpirit_Wolf_Dire_C>();
	}
};
static_assert(alignof(ASpirit_Wolf_Dire_C) == 0x000010, "Wrong alignment on ASpirit_Wolf_Dire_C");
static_assert(sizeof(ASpirit_Wolf_Dire_C) == 0x001DA0, "Wrong size on ASpirit_Wolf_Dire_C");
static_assert(offsetof(ASpirit_Wolf_Dire_C, UberGraphFrame_Spirit_Wolf_Dire_C) == 0x001D98, "Member 'ASpirit_Wolf_Dire_C::UberGraphFrame_Spirit_Wolf_Dire_C' has a wrong offset!");

}

