#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TooltipSection_EvenBordered

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TooltipSection_EvenBordered.TooltipSection_EvenBordered_C
// 0x0000 (0x0120 - 0x0120)
class UTooltipSection_EvenBordered_C final : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TooltipSection_EvenBordered_C">();
	}
	static class UTooltipSection_EvenBordered_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTooltipSection_EvenBordered_C>();
	}
};
static_assert(alignof(UTooltipSection_EvenBordered_C) == 0x000010, "Wrong alignment on UTooltipSection_EvenBordered_C");
static_assert(sizeof(UTooltipSection_EvenBordered_C) == 0x000120, "Wrong size on UTooltipSection_EvenBordered_C");

}

