#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MinimapImageTile

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MinimapImageTile.WBP_MinimapImageTile_C
// 0x0000 (0x0370 - 0x0370)
class UWBP_MinimapImageTile_C final : public UMapImageTile
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MinimapImageTile_C">();
	}
	static class UWBP_MinimapImageTile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MinimapImageTile_C>();
	}
};
static_assert(alignof(UWBP_MinimapImageTile_C) == 0x000008, "Wrong alignment on UWBP_MinimapImageTile_C");
static_assert(sizeof(UWBP_MinimapImageTile_C) == 0x000370, "Wrong size on UWBP_MinimapImageTile_C");

}

