#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AdditionalNodeServices

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_AdditionalNodeServices.WBP_AdditionalNodeServices_C
// 0x0008 (0x0308 - 0x0300)
class UWBP_AdditionalNodeServices_C final : public UAdditionalNodeServices
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0300(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_WBP_AdditionalNodeServices(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_AdditionalNodeServices_C">();
	}
	static class UWBP_AdditionalNodeServices_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_AdditionalNodeServices_C>();
	}
};
static_assert(alignof(UWBP_AdditionalNodeServices_C) == 0x000008, "Wrong alignment on UWBP_AdditionalNodeServices_C");
static_assert(sizeof(UWBP_AdditionalNodeServices_C) == 0x000308, "Wrong size on UWBP_AdditionalNodeServices_C");
static_assert(offsetof(UWBP_AdditionalNodeServices_C, UberGraphFrame) == 0x000300, "Member 'UWBP_AdditionalNodeServices_C::UberGraphFrame' has a wrong offset!");

}

