#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ItemFrontEndSlot

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ItemFrontEndSlot.WBP_ItemFrontEndSlot_C
// 0x0000 (0x04B8 - 0x04B8)
class UWBP_ItemFrontEndSlot_C final : public UItemFrontEndSlot
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ItemFrontEndSlot_C">();
	}
	static class UWBP_ItemFrontEndSlot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ItemFrontEndSlot_C>();
	}
};
static_assert(alignof(UWBP_ItemFrontEndSlot_C) == 0x000008, "Wrong alignment on UWBP_ItemFrontEndSlot_C");
static_assert(sizeof(UWBP_ItemFrontEndSlot_C) == 0x0004B8, "Wrong size on UWBP_ItemFrontEndSlot_C");

}

