#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CS_CharacterEntry

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CS_CharacterEntry.WBP_CS_CharacterEntry_C
// 0x0000 (0x0618 - 0x0618)
class UWBP_CS_CharacterEntry_C final : public UCS_CharacterEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CS_CharacterEntry_C">();
	}
	static class UWBP_CS_CharacterEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CS_CharacterEntry_C>();
	}
};
static_assert(alignof(UWBP_CS_CharacterEntry_C) == 0x000008, "Wrong alignment on UWBP_CS_CharacterEntry_C");
static_assert(sizeof(UWBP_CS_CharacterEntry_C) == 0x000618, "Wrong size on UWBP_CS_CharacterEntry_C");

}

