#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TaxSlider

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TaxSlider.WBP_TaxSlider_C
// 0x0008 (0x03E8 - 0x03E0)
class UWBP_TaxSlider_C final : public UTaxSlider
{
public:
	class UCommonBorder*                          B_Main;                                            // 0x03E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UCommonBorder* GetBorder();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_TaxSlider_C">();
	}
	static class UWBP_TaxSlider_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TaxSlider_C>();
	}
};
static_assert(alignof(UWBP_TaxSlider_C) == 0x000008, "Wrong alignment on UWBP_TaxSlider_C");
static_assert(sizeof(UWBP_TaxSlider_C) == 0x0003E8, "Wrong size on UWBP_TaxSlider_C");
static_assert(offsetof(UWBP_TaxSlider_C, B_Main) == 0x0003E0, "Member 'UWBP_TaxSlider_C::B_Main' has a wrong offset!");

}

