#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GlobalWarLeaderboard

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_GlobalWarLeaderboard.WBP_GlobalWarLeaderboard_C
// 0x0010 (0x0370 - 0x0360)
class UWBP_GlobalWarLeaderboard_C final : public UGlobalWarLeaderboard
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0360(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_ScrollWindow_NoFrame_C*            ScrollWindow;                                      // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_WBP_GlobalWarLeaderboard(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_GlobalWarLeaderboard_C">();
	}
	static class UWBP_GlobalWarLeaderboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GlobalWarLeaderboard_C>();
	}
};
static_assert(alignof(UWBP_GlobalWarLeaderboard_C) == 0x000008, "Wrong alignment on UWBP_GlobalWarLeaderboard_C");
static_assert(sizeof(UWBP_GlobalWarLeaderboard_C) == 0x000370, "Wrong size on UWBP_GlobalWarLeaderboard_C");
static_assert(offsetof(UWBP_GlobalWarLeaderboard_C, UberGraphFrame) == 0x000360, "Member 'UWBP_GlobalWarLeaderboard_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_GlobalWarLeaderboard_C, ScrollWindow) == 0x000368, "Member 'UWBP_GlobalWarLeaderboard_C::ScrollWindow' has a wrong offset!");

}

