#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SavedHudProfilesMenu

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SavedHudProfilesMenu.WBP_SavedHudProfilesMenu_C
// 0x0000 (0x0308 - 0x0308)
class UWBP_SavedHudProfilesMenu_C final : public USavedHudProfilesMenu
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_SavedHudProfilesMenu_C">();
	}
	static class UWBP_SavedHudProfilesMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SavedHudProfilesMenu_C>();
	}
};
static_assert(alignof(UWBP_SavedHudProfilesMenu_C) == 0x000008, "Wrong alignment on UWBP_SavedHudProfilesMenu_C");
static_assert(sizeof(UWBP_SavedHudProfilesMenu_C) == 0x000308, "Wrong size on UWBP_SavedHudProfilesMenu_C");

}

