#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CommissionConditionalIcon

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CommissionConditionalIcon.WBP_CommissionConditionalIcon_C
// 0x0000 (0x02F8 - 0x02F8)
class UWBP_CommissionConditionalIcon_C final : public UCommissionConditionalIcon
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CommissionConditionalIcon_C">();
	}
	static class UWBP_CommissionConditionalIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CommissionConditionalIcon_C>();
	}
};
static_assert(alignof(UWBP_CommissionConditionalIcon_C) == 0x000008, "Wrong alignment on UWBP_CommissionConditionalIcon_C");
static_assert(sizeof(UWBP_CommissionConditionalIcon_C) == 0x0002F8, "Wrong size on UWBP_CommissionConditionalIcon_C");

}

