#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ServicesProvidedEntry

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ServicesProvidedEntry.WBP_ServicesProvidedEntry_C
// 0x0008 (0x0338 - 0x0330)
class UWBP_ServicesProvidedEntry_C final : public UServicesProvidedEntry
{
public:
	class UCommonBorder*                          AlternatingBG;                                     // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	class UCommonBorder* GetBorder();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ServicesProvidedEntry_C">();
	}
	static class UWBP_ServicesProvidedEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ServicesProvidedEntry_C>();
	}
};
static_assert(alignof(UWBP_ServicesProvidedEntry_C) == 0x000008, "Wrong alignment on UWBP_ServicesProvidedEntry_C");
static_assert(sizeof(UWBP_ServicesProvidedEntry_C) == 0x000338, "Wrong size on UWBP_ServicesProvidedEntry_C");
static_assert(offsetof(UWBP_ServicesProvidedEntry_C, AlternatingBG) == 0x000330, "Member 'UWBP_ServicesProvidedEntry_C::AlternatingBG' has a wrong offset!");

}

