#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TimerTextBlock

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameSystemsPlugin_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TimerTextBlock.WBP_TimerTextBlock_C
// 0x0008 (0x03F8 - 0x03F0)
class UWBP_TimerTextBlock_C final : public UTimerTextBlock
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ConstructSettings(class UTextBlock* Widget, bool IsVisible_0, const class FString& Text, bool HasPostfix);
	void ExecuteUbergraph_WBP_TimerTextBlock(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_TimerTextBlock_C">();
	}
	static class UWBP_TimerTextBlock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TimerTextBlock_C>();
	}
};
static_assert(alignof(UWBP_TimerTextBlock_C) == 0x000008, "Wrong alignment on UWBP_TimerTextBlock_C");
static_assert(sizeof(UWBP_TimerTextBlock_C) == 0x0003F8, "Wrong size on UWBP_TimerTextBlock_C");
static_assert(offsetof(UWBP_TimerTextBlock_C, UberGraphFrame) == 0x0003F0, "Member 'UWBP_TimerTextBlock_C::UberGraphFrame' has a wrong offset!");

}

