#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_KeyBindingsWrapBox

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_KeyBindingsWrapBox.WBP_KeyBindingsWrapBox_C
// 0x0010 (0x0388 - 0x0378)
class UWBP_KeyBindingsWrapBox_C final : public ULabeledWrapBox
{
public:
	class UCheckBox*                              EnableCharacterSpecificCheckBox;                   // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_KeyBindingChangeOverlay_C*         KeyBindingChangeOverlay;                           // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_KeyBindingsWrapBox_C">();
	}
	static class UWBP_KeyBindingsWrapBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_KeyBindingsWrapBox_C>();
	}
};
static_assert(alignof(UWBP_KeyBindingsWrapBox_C) == 0x000008, "Wrong alignment on UWBP_KeyBindingsWrapBox_C");
static_assert(sizeof(UWBP_KeyBindingsWrapBox_C) == 0x000388, "Wrong size on UWBP_KeyBindingsWrapBox_C");
static_assert(offsetof(UWBP_KeyBindingsWrapBox_C, EnableCharacterSpecificCheckBox) == 0x000378, "Member 'UWBP_KeyBindingsWrapBox_C::EnableCharacterSpecificCheckBox' has a wrong offset!");
static_assert(offsetof(UWBP_KeyBindingsWrapBox_C, KeyBindingChangeOverlay) == 0x000380, "Member 'UWBP_KeyBindingsWrapBox_C::KeyBindingChangeOverlay' has a wrong offset!");

}

