#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AlertPrompt

#include "Basic.hpp"

#include "GameSystemsPlugin_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_AlertPrompt.WBP_AlertPrompt_C
// 0x0008 (0x03C8 - 0x03C0)
class UWBP_AlertPrompt_C final : public UAlertPrompt
{
public:
	class UOverlay*                               ContentOverlay;                                    // 0x03C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_AlertPrompt_C">();
	}
	static class UWBP_AlertPrompt_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_AlertPrompt_C>();
	}
};
static_assert(alignof(UWBP_AlertPrompt_C) == 0x000008, "Wrong alignment on UWBP_AlertPrompt_C");
static_assert(sizeof(UWBP_AlertPrompt_C) == 0x0003C8, "Wrong size on UWBP_AlertPrompt_C");
static_assert(offsetof(UWBP_AlertPrompt_C, ContentOverlay) == 0x0003C0, "Member 'UWBP_AlertPrompt_C::ContentOverlay' has a wrong offset!");

}

