#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WindowTutorialText

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WindowTutorialText.WindowTutorialText_C
// 0x0000 (0x01D0 - 0x01D0)
class UWindowTutorialText_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WindowTutorialText_C">();
	}
	static class UWindowTutorialText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWindowTutorialText_C>();
	}
};
static_assert(alignof(UWindowTutorialText_C) == 0x000010, "Wrong alignment on UWindowTutorialText_C");
static_assert(sizeof(UWindowTutorialText_C) == 0x0001D0, "Wrong size on UWindowTutorialText_C");

}

